export const COMMENT_POSITION_DELAY_MS = 350;
export const COMMENT_POSITION_WAIT_MS = 3000;
export const COMMENT_POSITION_TOTAL_MS = COMMENT_POSITION_DELAY_MS + COMMENT_POSITION_WAIT_MS;
export const COMMENT_POSITION_SETTLE_MS = 300;
